name: partridge
channels:
  - conda-forge
  - bioconda
  - nodefaults
dependencies:
  - python=3.13
  - pip
  - r-base=4.5
  - r-tidyverse=2.0.0
  - r-openxlsx=4.2.8.1
  - bioconda::bioconductor-genomicranges=1.62.1
  - bioconda::bioconductor-biostrings=2.78.0
  - bioconda::hmmer=3.4
  - bioconda::samtools=1.22
  - bioconda::bwa-mem2=2.3
  - pip:
      - et_xmlfile==2.0.0
      - numpy==2.2.4
      - openpyxl==3.1.5
      - pandas==2.2.3
      - psutil==6.1.1
      - pyhmmer==0.11.0
      - pysam==0.23.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - tzdata==2025.2